### ISSUE TITLE
Error de login con facebook y twitter

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#1]
Al intentar iniciar sesion utilizando twitter y facebook muestra una pantalla amarilla de error para facebook y un mensaje de error de twitter

**Comment by jmmartinez1985** [comment]
Se debe cambiar los url de redirect de twitter, se actualizo a uno válido, el cambio sera subido al control de cambios.

**Comment by jmmartinez1985** [comment]
![twitter_issue](https://f.cloud.github.com/assets/5157691/1123433/19726c8c-1aef-11e3-8481-a3cb72d7e353.JPG)
