### ISSUE TITLE
No se deben borrar los anuncios

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#100]
Creo que deberiamos cambiarle el estado al anuncio, por ejemplo estado "borrado" y a todas sus dependencias (solicitudes, reviews, etc) que todos tengan el mismo estado y que este no sea recuperable para el usuario, es decir no se le pueda volver a cambiar el estado, que este no aparezca en las búsquedas ni mucho menos, pero que se conserve en la base de datos
Comentame @jmmartinez1985 se podría hacer esto? implicaría mucho esfuerzo ? lo demás para un segundo release ? cuentame!

**Comment by jmmartinez1985** [comment]
Si se podria ejecutar un transacción donde se cambia de estatus a todos estos vinculos y yap, solo que yo habia dejado que si los anuncios tienen reviews no debieras eliminarlos, es mas a los reviews no inactivarlos ya que sirve para otras personas, pero aqui esta el detalle que entonces se deberia valorar al anunciantes ya que el anuncio que era valorado ya esta inactivo y no es visible.

**Comment by jmmartinez1985** [comment]
Hare un update de todas las referencias por el estatus borrado.

**Comment by jmmartinez1985** [comment]
Listo, pero tienes un problema de styles cuando borras un anuncio de amplia descripcion de jode y se acorta el BS
