### ISSUE TITLE
Error al borrar un anuncio

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#101]
me sale un error al borrar el anuncio, aparentemente no puede encontrar la vista
ingrese con jo.mi.ma y trate de eliminar un anuncio

![image](https://f.cloud.github.com/assets/713416/1706358/f0ffa39c-60ed-11e3-81fa-642f56c1c184.png)

**Comment by jmmartinez1985** [comment]
Al borrar el no debe buscar un vista por el contrario solo debiera llamar la accion por javascript y yap. Hay que revisar.

**Comment by IsrraBanton** [comment]
no pasa por el debug...!

**Comment by jmmartinez1985** [comment]
// POST: /Anuncios/Delete/5
        [Authorize(Roles = "Users")]
        //[HttpPost, ActionName("Delete, Admin")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)

Listo use un nombre no el actionname del POST, por que ... ni idea jaajjajaa....
