### ISSUE TITLE
Verificar cuando se borra un anuncio se desalinea la tabla

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#102]
Cuando se borra se jode el span

![image](https://f.cloud.github.com/assets/5157691/1770308/eb66f4f6-6789-11e3-9e5a-cc475fba4fc7.png)

**Comment by IsrraBanton** [comment]
intento borrar y me manda este error...
![image](https://f.cloud.github.com/assets/713416/1828065/a8de4586-724b-11e3-8a4e-46b79452b1de.png)
