### ISSUE TITLE
Escenerios de Prueba --- Usuarios no autenticados.

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#103]
Usuario no autenticado

Seguridad
    - Menú CapitalLetter
    - Iniciar Sesión
        - Intentos
    - Registro
        - Validaciones de correo (Existencia)
        - Strong Password
        - Checked de Terminos
    - Olvidar contraseña
        - Verificación de correo electronico
        - Ortografia de correo
        - Cambio de contraseña
        - Se debe resetear, pero el usuario cuando entra debe cambiarla
    - Autenticación Facebook
        - Procedimiento
            - Validación en base de datos de cuenta
            - Ingreso
    - Autenticación Twitter
        - Procedimiento
            - Validación en base de datos de cuenta
            - Ingreso
- Ayuda
  - Contenido (vista, descarga de ayuda)
  - Ayuda debe ir a FAQ
- Home Page
  - Menú CapitalLetter
    -Busqueda avanzada
    -despliegue de data
    -despliegue de existencia de datos (plantilla)
    -verificación de tipos de busqueda.
    -acción buton se lupa (busqueda)
    -Listado
    -Verificación de despligue por página
    -Validación de botones leer mas y solicitar
        -Ruta.
        -Existencia de página
    -Paginación
        -Ortografia.
        -Correcto despligue por número de anuncios por página
        -desplazamiento correcto
    -Opcion Leer Más
        - Libre despliegue
    -Opcion Solicitar
        - Debe autenticar
- Bloq
  - Menú CapitalLetter
  - Despliegue de Tweet SMA
    -Posicionamiento en página (75%)
- FAQ
  - Menú CapitalLetter
  - Despliegue de FAQ
    - Ortografia
    - Cantidad de FAQ
      - Paginación
- Contactenos
  - Formulario de contactos
  - Información de ubicación.
    - Data de localización
    - Mapa

**Comment by IsrraBanton** [comment]
yo intenté sintetizar esto de una manera fácil para un usuario normal (para pedir a gente no sepa de tecnologia que nos ayude a testear!)

Usuario No Registrado
-- Buscar anuncios
-- Registro con correo electrónico
-- Registro con twitter
-- Registro con facebook
-- Contactar con sma (contactenos)
-- Leer los faqs
-- Leer el blog

Usuario Registrado
-- Buscar anuncios
-- Solicitar anuncios
-- Atender Solicitudes
-- Calificar el servicio
-- Dejar comentarios
-- Responder comentarios
-- Registrar anuncios
-- Administrar anuncios
-- Administrar solicitudes
-- Cambio de contraseña

Usuario Administrador
-- Registrar/editar
    -- Categorias
    -- Subcategorias
    -- Faqs
    -- Membresia
-- Administrar anuncios publicados
-- Modificar datos de compañia
-- Responder a contactos

**Comment by IsrraBanton** [comment]
La web esta arriba en esta dirección
http://isrrasma-001-site1.smarterasp.net/

**Comment by jmmartinez1985** [comment]
Completado.

Se debe iniciar nueva vuelta de bugs
