### ISSUE TITLE
Pantallas - Volver

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#105]
Algunos volver no deberías regresar al /HOME.

Ya que si yo estoy viendo detalles de un anuncio, debo volver al listado de anuncios no al /HOME.

**Comment by IsrraBanton** [comment]
en el caso de que seas un usuario no registrado debería enviarte al home, en otros casos no se, por ejemplo yo soy un usuario registrado, el sistema lo sabe y yo toy buscando para contratar a alguien, cuando le doy volver despues de haber leido un servicio que no me interesó y me envia a mi lista de anuncios por ejemplo....estaría mal, porque lo que estoy haciendo es buscando anuncios para contratar...

Hay que ver bien esos escenarios

**Comment by jmmartinez1985** [comment]
Abria que hacer un pequeño IF, cuando sea autenticado o no

**Comment by IsrraBanton** [comment]
y definir en que pantallas va el if.
creo que esto saldrá de las pruebas.

**Comment by jmmartinez1985** [comment]
O no se si se puede hacer un Filter para esto?... o que me importa que todos vuelvan al home excepto el details de anuncios

**Comment by IsrraBanton** [comment]
el details de anuncio es donde yo como usuario que busca un servicio intento buscar algun anuncio que me parezca interesante, entiendo que el regresar me deberia mandar al home ya que sino a donde me enviara ?

**Comment by jmmartinez1985** [comment]
Los volver de ANUNCIOS: DETAILS/CREATE/EDIT que vuelvan al INDEX del anuncio, todos lo demas al home.

**Comment by IsrraBanton** [comment]
Listo para la versión del 22 de enero
