### ISSUE TITLE
Home -- Anuncion -- Boton Lupa

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#107]
Este botón no tiene funcionalidad.

o se quita o se le incorpora a la búsqueda.

**Comment by IsrraBanton** [comment]
va por fuera, lo eliminare

**Comment by jmmartinez1985** [comment]
No se puede eliminar, ya que revise que la busqueda solo funciona dentro de la información que se desplego, por ende la finalidad de la lupa quedaría en que la persona escribe cualquier boludez y buscaría, osea iria contra la DB y haria como un LIKE con la descripción.

**Comment by IsrraBanton** [comment]
ummmm entonces hay que programarlo por que por lo que vi no estaba programado o si ???

**Comment by IsrraBanton** [comment]
ya lo regresé pues lo habia eliminado
