### ISSUE TITLE
No existe acuerdo ni condiciones

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#110]
Debe haber una página de contenido de los acuerdo y condiciones.

debe ser:
- HTML estatico o
-  MVC.

**Comment by IsrraBanton** [comment]
mvc mejor, asi puedo poner una pagina bonita con bootstrap... digo yo.... esta ta facil dejame esto a mi XD

**Comment by IsrraBanton** [comment]
listo, me copie de el de unify, obviamente el texto hace falta pero ya lo cerraré o no se si cerrarlo creo que necesitamos la redaccion de un abogado no tengo la mas remota idea de que se coloquen en esas clausulas.
