### ISSUE TITLE
No permitir creación de cuenta - Usuario Autenticado

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#111]
No se debe permitir creación de cuenta si ya existe un usuario en sesión.

Procedimiento: Se debe enviar una pantalla de confirmación indicando que quieres salir de la sesión actual

**Comment by IsrraBanton** [comment]
Ey pero cuando tas loggeado no puedes iniciar sesion porque desaparece el link de iniciar sesion

**Comment by jmmartinez1985** [comment]
No ocurré, pense que si escribias la direccion.

No pondre como enhancement

**Comment by jmmartinez1985** [comment]
Se cierra, la sesion actual y queda la nueva, se debiera crear con captcha, para evitar algun robot.

**Comment by IsrraBanton** [comment]
listo trolo!!! ya agregué los captcha y cuando tas loggeado intentas registrar otra cuenta te desloggea lo mismo si tratas de iniciar sesion con otra cuenta.
