### ISSUE TITLE
Contactenos Create

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#114]
No se lleno ningun campo del formulario y se presiono create.

La pantalla queda congelada en loading.

![image](https://f.cloud.github.com/assets/5157691/1950142/89ce93da-8137-11e3-8384-9ab1717a312a.png)

**Comment by IsrraBanton** [comment]
ya lo solucioné, pasa que no se estaban validando porque tuve que sacar el boton del begin form para darle un metodo de js, por ende no se ejecutaban los validators y se iba al carajo.
Le agregue doble validacion, si es que alguno de los requeridos esta en blanco manda un gritter que tiene que llenar datos, y si igual lo envia pero el controlador encuentra el modelo invalido igual manda un gritter disk on laope llena todos los datos o que xopa!!!! 
seria bueno poder hacer que los validators de la pagina se activaran digo pa eso los declare en el modal extension pero weno... me comentas....!!!! @jmmartinez1985 si no se puede entonces ya estaria cerrado la incidencia porque lo valide de otras dos formas, solo faltaria subir la version
