### ISSUE TITLE
Paginación en las lista

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#12]
No existe una paginación en las lista.

implementar bootstrap o otro mecanismo de paginación.

**Comment by jmmartinez1985** [comment]
Isrra, hara la plantilla de unify

**Comment by IsrraBanton** [comment]
este es el html para la paginación, la parte del js es tuya Jose!
Elegí centrada y de tamaño grande ya que cada línea de anuncio ocupa bastante espacio, pensé que muy pequeño se podría perder. Sino cualquier cosa solo se le quita el "large" de la clase del div 

<div class="pagination pagination-large pagination-centered">
                <ul>
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>

**Comment by jmmartinez1985** [comment]
Se implemento paginacion en los anuncios, creacion de javascript e implementacion de css  y plugin, se debe implementar dentro del administrador a los catalogos.
