### ISSUE TITLE
Create anuncios -- FALLA

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#120]
Tanto como la carga y como la creación se debe dar por el incidente del Javascript de getinformationcompany.

![image](https://f.cloud.github.com/assets/5157691/1950509/683d38b6-814b-11e3-8edc-1e9d34d9e3ab.png)

**Comment by IsrraBanton** [comment]
cerrado por que ya inclui los scripts que faltaban!
