### ISSUE TITLE
Cambiar la plantilla de solicitudes de servicio cuando esta empty

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#122]
Cuando no se tiene solicitudes actuales, llenar el espacio con algo de basura o propaganda o darle unos tips al usuario en ese momento, cualquiera que no sea la definición de tablas y en blanco.

Opciones:
1. Publicidad.
2. Mensaje alternativos.
3. Darle algo a conocer de SMA.

**Comment by IsrraBanton** [comment]
le agregue algo de info del mismo Service Market ... igual para los anuncios publicados cuando no tienen ninguno
