### ISSUE TITLE
Usuarios sin nombre

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#129]
Que no se permita la creacion de usuarios sin nombre (esto cuando se registran usando facebook o twitter)

**Comment by IsrraBanton** [comment]
Creo que habria que incluir al menos el campo nombre en la pantalla de registro y que cuando redireccione mande a la pagina del perfil

**Comment by IsrraBanton** [comment]
el redirect ya lo puse en el codigo, pero no toy seguro como agregar el nombre en ese modelo, me ilustraras luego como se hace esa demencia

**Comment by jmmartinez1985** [comment]
Puse una alerta para esto, ademas hay que poner un default value en la base de datos para el nombre que diga, "NO Asignado" algo asi...

**Comment by jmmartinez1985** [comment]
Piensa que la alerta BS esta bien, con un link que lleve a la pagina que editas tu perfil? Comenta @IsrraBanton

**Comment by IsrraBanton** [comment]
Cual alerta??? como la veo ? @jmmartinez1985

**Comment by IsrraBanton** [comment]
listo
