### ISSUE TITLE
Información de perfil erronea

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#130]
Cuando se registró el usuario se le colocó país panamá, cuando se entra a la información del usuario muestra afganistan

**Comment by jmmartinez1985** [comment]
No se puede reproducir

**Comment by IsrraBanton** [comment]
Como que no!!! mira....!!!!
![image](https://f.cloud.github.com/assets/713416/1998546/53bebc82-8535-11e3-8b40-c4704dd78a1c.png)

dice nacionalidad afganistan, yo coloco isla caiman, la guardo

![image](https://f.cloud.github.com/assets/713416/1998559/ae69c47e-8535-11e3-9c2b-3a3a77eba77b.png)

salgo y vuelvo a entrar y dice afganistan de nuevo

![image](https://f.cloud.github.com/assets/713416/1998562/c220ff96-8535-11e3-999c-d60a767179d7.png)

**Comment by jmmartinez1985** [comment]
OK, entonces lo veremos en una prueba LIVE.

**Comment by jmmartinez1985** [comment]
Se cierra
