### ISSUE TITLE
Mis anuncios publicados vacio

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#135]
Cuando no has publicado ningun anuncio sería bueno que en vez del texto que dice que no tiene anuncios publicados, puede haber un texto con un link que le permita ir a la página de registro de anuncios

**Comment by jmmartinez1985** [comment]
Lo cerraste pero que hiciste??????

**Comment by jmmartinez1985** [comment]
Por favor indicarme como procediste?

**Comment by IsrraBanton** [comment]
calma fiera, esto está para la versión de hoy! ya lo programé pero no lo subi, y lo que hice fue colocar un texto que promueva crear anuncios y descripcion de SMA
