### ISSUE TITLE
Colocar el registro con facebook o twiter en la pagina de registro

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#136]
Si yo soy un usuario no registrado y hago clic en registrarme solo me presenta la opcion de un nuevo registro de SMA. Sin embargo, en la de registro esta iniciar sesion con facebook y twitter, pero si aun no me he registrado yo no llegaré a esa pagina y yo me quiero registrar con twitter.
Hay que colocar la opcion de registro con twitter y facebook en la pagina de registro

**Comment by jmmartinez1985** [comment]
Esto debe ser trasparente para el usuario ya que el se esta autenticando con facebook o twitter, por eso es que digo, con que cuenta o contraseña queda, es mas yo creo que existe una tabla con este vinculo a la tabla userprofile, por ende hay que validar.

**Comment by IsrraBanton** [comment]
ey @jmmartinez1985 no entendi ??? que tengo que hacer entonces ???? yo coloqué el inicio de sesión con tw y fb en la pagina de registro porque alguien que haga clic en registro solo ve la opcion de poner su correo.... entonces parece que no te puedes registrar con mas nada... por eso lo coloqué alli y cerre el incidente

**Comment by jmmartinez1985** [comment]
Revisaré bien el incidente, ya que al parece fue que yo me registre, y 
trate de entrar por el login, algo asi... fue, pero si... luego de esto se 
debe enviar igual a la pantalla de edición de perfil, se tiene que tener en 
cuenta que para TW tienes que usar el correo como username para nosotros.
