### ISSUE TITLE
Eliminacion de catalogos

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#138]
No estan programadas las eliminaciones de los catalogos (categoria, subcategoria, faqs y membresia) si no se van a eliminar se debe quitar la opcion del administrador

**Comment by IsrraBanton** [comment]
Listo en la version de mañana 22 de enero

**Comment by jmmartinez1985** [comment]
Todos los catalogos funcionan de que manera: SYNC o ASYNC (ajax)?
