### ISSUE TITLE
Imagen en los anuncios

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#139]
En la lista de anuncios no se debe mostrar ningún anuncio sin imagen. La logica sería la siguiente:
Imagen del anuncio (cualquiera puede ser aleatoria o siempre la primera)
Si el anuncio no tiene imagenes entonces se muestra la imagen del perfil del usuario y si tampoco tiene entonces se mostrará una imagen default como la que se muestra en el perfil para los usuarios que no tenga imagen

**Comment by jmmartinez1985** [comment]
Creo que ya lo tienes asi @IsrraBanton
