### ISSUE TITLE
Habilitar Search Lista del Administrador

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#14]
Se debe igual que en los anuncios habilitar las búsquedas rápidas en los despliegue de catalogos.

**Comment by jmmartinez1985** [comment]
Integrar search de unify.

**Comment by jmmartinez1985** [comment]
Se debe hacer implementacion en demas, dependo de que @IsrraBanton haga el look and feel

**Comment by IsrraBanton** [comment]
ya implemente el look and feel @jmmartinez1985

**Comment by jmmartinez1985** [comment]
Listo ya esta implementado, la vista  getuser
