### ISSUE TITLE
Imagen de perfil

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#140]
Revisar la posibilidad de subir la imagen de perfil en un solo paso pues seleccionarla y luego cargarla o en realidad subirla se presta para confusiones y es engorroso

**Comment by jmmartinez1985** [comment]
Propon algo?

**Comment by IsrraBanton** [comment]
que el boton de seleccionar imagen haga el proceso completo(selecciona y sube de una vez)

**Comment by IsrraBanton** [comment]
no se si sea posible

**Comment by jmmartinez1985** [comment]
Esto es mucha vuelta, pienso que se puede quedar asi, por el momento ya que en cuanto a funcionalidad anda.

**Comment by IsrraBanton** [comment]
weno cerrado pues
