### ISSUE TITLE
Tiempo de caducidad de anuncios

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#144]
Los anuncios deben expirar desde el día que se crearon a 3 meses o el tiempo pactados, una vez expirados y si la persona quiere activarlos nuevamente la fecha de activación debe pasar a ser la fecha de creación del anuncio y por ende automaticamente se le expira siempre cada mes por tipo de membresia.

Se debe crear un campo de fecha de caducidad, algo automatico.

**Comment by IsrraBanton** [comment]
cerrado por duplicado
