### ISSUE TITLE
Resaltar error en rojo en creacion de anuncios

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#147]
Verificar porque no se pone en rojo unos textbox.

Prueba dejando todo en blanco.

**Comment by IsrraBanton** [comment]
por cosas de la vida los textbox multiline no aplican en este caso, siempre he visto que ellos no se ponen rojo, y el otro que no ves en rojo es porque esta seleccionado y esta azul y el otro de telefono no es obligatorio.

Voy agregar un estilo para que resalte los textbox multiline tambien!!!
