### ISSUE TITLE
Callback url de facebook login no funciona

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#153]
![image](https://f.cloud.github.com/assets/5157691/1991937/ae30faee-84aa-11e3-992d-95fb498abf36.png)

**Comment by IsrraBanton** [comment]
el problema es que en la aplicacion de facebook apunta a localhost... intenté ponerle la direccion del sma cloud pero los de facebook se odia con smartasp.net y me dice que isrrasma-001-site1.smarterasp.net es una dirección perjudicial y que puede tener bichos... y no me deja ponerla, asi que pa probarlo web hay que comprar un dominio.... o probarlo local, desde localhost/smaweb (sin puertos porque sino tambien jode!)

**Comment by jmmartinez1985** [comment]
No me anda el localhost, ya eso que describiste me lo habias comunicado anteriormente.

**Comment by IsrraBanton** [comment]
eres un plomo!!! aca funciona bien!!! ahora me muestras por el team viewer pa ver que trolada tas haciendo!!!
