### ISSUE TITLE
Procedimiento de verificación de cuentas

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#154]
Se debe hacer un procedimiento que verifique todas las cuentas que están por expirar y notificar al usuario: las que estan por expirar y expirar las que ya sobrepasaron el tiempo.

**Comment by IsrraBanton** [comment]
ey como eres una vaca en sql yo voy hacer el SP que desactive las cuentas pues

**Comment by IsrraBanton** [comment]
ya te mande al correo los SP
