### ISSUE TITLE
Incidente en la creación de anuncios-- FIX Edit Anuncio

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#159]
Se debe corregir el mismo incidente de CREATE anuncios en Edit Anuncio, ya que probablemente tiene el mismo problema.

**Comment by IsrraBanton** [comment]
cual era el problema no lo recuerdo ??? @jmmartinez1985

**Comment by jmmartinez1985** [comment]
OK, que no te marcaba las validaciones en los dropdownlist y te duplicaba la pagina en ella misma.

Pero no toques nada aqui... yo estoy trabajando en el

**Comment by IsrraBanton** [comment]
ok

**Comment by jmmartinez1985** [comment]
Listo
