### ISSUE TITLE
BUGS de CSS en plantillas

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#161]
Plantillas de confirmacion y expiración no tomas los estilos CSS.

Verificar

**Comment by IsrraBanton** [comment]
revisa a ver si ya esta listo

**Comment by jmmartinez1985** [comment]
Más bugs... hay algo mas alli

![image](https://f.cloud.github.com/assets/5157691/2006082/df6c84be-8709-11e3-8ea3-5ab8434db9da.png)

**Comment by jmmartinez1985** [comment]
No puedes tirar ese CSS asi a lo vulgar tienes que armar un CSS file.

Nota: Haz prueba de estos cambios.

**Comment by jmmartinez1985** [comment]
La vista hay que configurarla para enviar el HTML... algo asi...
http://aboutcode.net/postal/multi-part.html

**Comment by IsrraBanton** [comment]
para que funcionara tuve que ponerle los estilos en cada tag HMTL, eso quedo un html horrible que pa leerlo es un dolor de eggs, pero ya ta listo, las otras dos las pasé a xslt como habiamos quedado. 
Prueba y avisas pues
