### ISSUE TITLE
Agregar funcionalidad de web api en admin

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#163]
Se debe agregar ambas funcionalidades al menu administrador para envio de notificaciones y expiración de cuentas.

Se debe corregir la ruta de los xslt.

Agrega lo demas y me asignas esta tarea.

**Comment by IsrraBanton** [comment]
agregué la ruta base en el webconfig y la imagen que va en el correo y el link de comprar membresias. Con esto ya debería estar funcionando pero por algun motivo que desconozco no se envian los correos, pero no envia error.
checkealo si puedes para revisar que es lo que está mal.

**Comment by jmmartinez1985** [comment]
OK, listo yo reviso luego a ver!

**Comment by IsrraBanton** [comment]
las funcionalidades estan agregadas en el catalogo de membresía (dos botones)
