### ISSUE TITLE
No es posible este link

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#164]
C:\Users\Logic\Documents\GitHub\SMASolution\SMAWeb\

No es posible este link, ya que no sabes donde quedará en hosting esa rutu, por ende tienes que trabajar en la ruta relativa que te el site y la ubicación de carpetas

**Comment by jmmartinez1985** [comment]
![Uploading image.png . . .]()

**Comment by jmmartinez1985** [comment]
Ese es tu error.... Man

**Comment by IsrraBanton** [comment]
la ruta esta asi por que apunta a mi pc, en tu pc sera distinta y cuando este en el web tiene que ser algo asi como smapanama.com/blablabla...
