### ISSUE TITLE
Imagen en logo de plantillas no sale

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#165]
El logo en las plantillas de correo no sale.

![image](https://f.cloud.github.com/assets/5157691/2079950/8b421b6a-8dd0-11e3-804d-8751b06c5fb9.png)

![image](https://f.cloud.github.com/assets/5157691/2079957/98d901ee-8dd0-11e3-91c9-8b1c6b0ddad7.png)

**Comment by IsrraBanton** [comment]
yo hice una prueba del html que genera la plantilla y está bien, mapea bien la imagen y todo, lo copie en un archivo html nuevo y se aprecia la imagen, pero cuando llega a hotmail el maldito pone otra imagen ramdom que no se que significa, habrá que probarlo cuando este en el servidor a ver si es que lo hace bien, yo creo que puede ser porque la imagen apunta a localhost y hotmail puede eliminar eso... quien sabe...

![image](https://f.cloud.github.com/assets/713416/2162077/e13766ac-94cd-11e3-80a5-d9f772d76e77.png)

**Comment by IsrraBanton** [comment]
no se estan enviando los emails, me intenté registrar y tampoco me envio el email, manda el siguiente error
The SMTP host was not specified.

alguna idea de que diablos paso ??? @jmmartinez1985

**Comment by IsrraBanton** [comment]
al parecer le faltaba la parte del webconfig que setea el smtp... ahora.. hay unos app settings donde esta eso pero no se porque igual mandaba este error... con esto cambiado ahora me sale el siguiente error

The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required. Learn more at

lo hice en desarrollo y funciona bien

**Comment by IsrraBanton** [comment]
mira esta demencia... me registre con una cuenta de outlook y otra de gmail
en outlook no se ve la imagen del logo y gmail si, te copio las evidencias
(la imagen esta quemada en el html que estoy enviando en el correo, pero outlook hace lo que le pica el huevo con las imagenes!)
![image](https://cloud.githubusercontent.com/assets/713416/2598811/5e158de8-bad0-11e3-8ad2-4a3e2544839e.png)

![image](https://cloud.githubusercontent.com/assets/713416/2598813/71b3fc18-bad0-11e3-92a5-c69355d720af.png)

se me ocurre una idea más, pero no se si funcione, voy a aplicarla para ver que xopa, y sino ya me cabrié de esa pendejada de outlook, no se que mas hacer!

**Comment by IsrraBanton** [comment]
friend no se que xaxa le pasa al maldito outlook.com, me cambia los estilos el carechimba ese!!! mira lo que puse...

<div style="background-image:url(http://isrrasma2-001-site1.smarterasp.net/Images/logo1-blue.png); background-repeat:no-repeat; width: 100%;height: 80px;" >
</div>

ya que cambiaba el src en los tags images... le puse la imagen de background a un div... pensé que podria funcionar... y mira el estilo que resuelve en mi bandeja...

<div style="background-repeat:no-repeat;width:100%;height:80px;">
</div>

es decir sin el url de la imagen...!!! que desgracia!!!!  

y en gmail lo hace peor... mira...

<div style="background-image:url(https://ci3.googleusercontent.com/proxy/PWHLGAjoc1feLwmRfJbD7B0VWYrmLlF_59AN8pL-xMU7w8h_kEIFJEo9B10wt1QB1yKlUGzzcbLJq5AjFIwN40tVjuL-C_qlKsJjCNCwWzUU5rrn_Q=s0-d-e1-ft#http://isrrasma2-001-site1.smarterasp.net/Images/logo1-blue.png);background-repeat:no-repeat;width:100%;min-height:80px" class="adM">
</div>

que hago con esto calderon??? alguna idea ???

**Comment by IsrraBanton** [comment]
@jmmartinez1985 weno yo creo que ya cerraré esto...! ya vi que no es la plantilla sino el mismo correo
