### ISSUE TITLE
No se carga la imagen de perfil

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#167]
No se carga la imagen de perfil, envia error

**Comment by IsrraBanton** [comment]
tienes el screen de pantalla ??? @jmmartinez1985

**Comment by IsrraBanton** [comment]
en que casos pasa esto ??? explicame mejor para poder resolver!!! @jmmartinez1985

**Comment by IsrraBanton** [comment]
en el servidor he intentado subir la imagen del perfil y me envia error, en el elmah almaceno lo siguiente
 Could not find a part of the path 'h:\root\home\isrrasma-001\www\SMA\FilesUploaded\Profiles\Sangre Fría Cover.jpg'.

 alguna idea @jmmartinez1985

**Comment by jmmartinez1985** [comment]
uufff @IsrraBanton eso quiere decir que no se pueden subir imagenes... o puede ser que la carpeta haya arriba no existe....

**Comment by IsrraBanton** [comment]
intento debbugear el httphandler que tiene el codigo para subir imagenes y no se como... le puse break points pero como que nunca pasan por alli no se...  hay que verificar a donde sube la imagen, creo que en vez de buscar el path c:/sma/etc.... deberia ser mas como www.sma.com/imagenes/etc... @jmmartinez1985

**Comment by jmmartinez1985** [comment]
Ya identifique el problema si verificas la carga de imagenes por medio del handler es diferente a la carga por medio del controllador UserProfile, Metodo:  public ActionResult UploadFiles()

**Comment by IsrraBanton** [comment]
no entendí... jajaja en conclusión que debo hacer ??? eyyy resuelve calderon!!! @jmmartinez1985

**Comment by jmmartinez1985** [comment]
Yo lo atenderé.!

**Comment by jmmartinez1985** [comment]
Mañana vere si resuelvo todos estos incidentes

**Comment by IsrraBanton** [comment]
viendo esto, creo que el problema era que no existia la carpeta... en el site ahorita si me deja subir las imagenes de perfil... pero weno tu detectaste algo que hay que arreglar en la programacion,asi que resuelve calderon! @jmmartinez1985

**Comment by jmmartinez1985** [comment]
@IsrraBanton create la carpeta igual, hare el cambio en lógica

**Comment by jmmartinez1985** [comment]
Listo, se hizo fix final
