### ISSUE TITLE
No indica nombre del recurso al eliminarlo de los anuncios

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#168]
Cuando se crea un anuncio y se le asignan recursos, no indica que se esta borrando... da ""

![image](https://f.cloud.github.com/assets/5157691/2145291/bcdfc616-939f-11e3-95ea-87e9bbe698cc.png)

**Comment by IsrraBanton** [comment]
listo, le puse bootbox a esta cosa y cambie unos textos que estaban en ingles
