### ISSUE TITLE
Hay imagenes que no cargan el preview en anuncios

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#169]
Cuando se carga la imagen no muestra preview.

![image](https://f.cloud.github.com/assets/5157691/2145299/f16b0616-939f-11e3-9cce-bc846b34ccf1.png)

**Comment by IsrraBanton** [comment]
te dejo esto porque yo no hice nada con el loader no quiero meter las de andar

**Comment by jmmartinez1985** [comment]
Verifique.
