### ISSUE TITLE
Creación de RSS

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#17]
Se debe crear un RSS de noticias o algo, ya que en el footer se tiene una subscripcion a ella a la cual se le estaría enviando informacion a la persona que se registre.

o se elimina o se administra, si es el caso hacer lo siguiente.
1. tabla en base de datos de este control.
2. administrar la informacion (controller, view, model)
3. Identificar la información que se le enviará (alguien debe administrar esto o tener pagina donde se cree html y el mismo se le envie al cliente subscrito por medio de plantilla html).

Proponer mas detalles....

**Comment by IsrraBanton** [comment]
derrepente mas adelante podríamos incluir esto, yo pienso que en esa parte podemos poner el nosotros... mision, vision, etc... no es mucho espacio asi que solo hay que escribir algo que nos tire flores XD

**Comment by jmmartinez1985** [comment]
Se retomará cuando se tenga tiempo

**Comment by IsrraBanton** [comment]
feature para una siguiente version
