### ISSUE TITLE
Habilitar Filtratado de Review

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#171]
Se debe habilitar la palabras ofensivas dentro del review, actualmente se tiene una lista hardcoded!

**Comment by jmmartinez1985** [comment]
Ofrezco 2 opciones para esta funcionalidad:
1. XML: Se puede configurar un  listado de palabras y cada vez que se agrega algo se cambian y se pasa el archivo a donde este ubicado 
2. Base de datos: Una tabla con la lista, pero tiene que darle mantenimiento a la tabla e incluir llamado dentro del menú de admin.

Escoge o propone?

**Comment by jmmartinez1985** [comment]
Esperando propuesta @IsrraBanton

**Comment by IsrraBanton** [comment]
Prefiero que sea por base de datos y que tenga su mantenimiento, porque un xml no es muy mantenible! @jmmartinez1985

**Comment by jmmartinez1985** [comment]
No se ha creado la tabla de esto, @IsrraBanton  por favor crear tabla y generar script para proceder hacer controlador.

**Comment by jmmartinez1985** [comment]
Listo, Falta controlador para mantenimiento.
