### ISSUE TITLE
NO funciona filtro de telefono

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#172]
NO esta funcionando la validación de numeros telefonicos en creacion de anuncios, antes me funcionaba, ya NO

**Comment by IsrraBanton** [comment]
habiamos quedado que se iban a eliminar esos formatos asi que los comenté, me estaba dando problemas al registrar los contactos pues por el regular expresion hacia del campo telefono obligatorio cuando no era asi. Por esto los comenté todos.
