### ISSUE TITLE
Error al intentar crear un nuevo anuncio

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#173]
Ingresé con el usuario isrrael_e@hotmail.com password 123456 y seleccione la opcion crear un nuevo anuncio y me muestra el mensaje que no es posible puesto que ya supere el maximo.

![image](https://f.cloud.github.com/assets/713416/2238463/e991f7f8-9bef-11e3-8299-3133eaae311c.png)

por esto me fui a mis anuncios publicados para modificar uno (ya que lo que queria probar era subir imagenes) y me sale el mensaje que no tengo anuncios, entonces como es posible ??? 

![image](https://f.cloud.github.com/assets/713416/2238459/c2a45492-9bef-11e3-9153-53a094494b4d.png)

en esta pantalla hay una opcion para crear nuevo anuncios y le hice clic y me mando a la creación de anuncios (en esta opcion tambien habría que agregarle la validación igual que en mis solicitudes porque esta el mismo mensaje)

**Comment by jmmartinez1985** [comment]
@IsrraBanton No se como te pasa esto, a mi si me anda muy bien.

**Comment by jmmartinez1985** [comment]
@IsrraBanton por favor vericaste bien esto.?

**Comment by IsrraBanton** [comment]
ey trolo, la validación que incluyes en el boton crear anuncios del menú, Mi service market/agregar anuncios, la debes de colocar en la pantalla de anuncios (index) pues alli te debe mostrar un grid con tus anuncios, pero si no tienes, te manda un mensaje disk crea tu anuncio, cuando le di clic desde alli si me dejó....

**Comment by IsrraBanton** [comment]
Ok lo explico mejor:
Fui a crear un anuncio y por algun extraño motivo el sistema me envio el mensaje no puedo crearse mas anuncios por que exceden la cantidad permitida de su plan... ok... ahora...!
yo intenté ir a mis anuncios publicados para borrar alguno y poder registrar uno nuevo...
alli fue cuando vi el error... no me salian anuncios publicados, entonces porque la validación anterior me decia que ya me habia excedido ??? y peor aún, 
cuando entras a mis anuncios publicados y no tienes anuncios, te muestra un texto que dice, no tienes anuncios, crea uno !!! cuando le di clic a crear un anuncio desde ese texto, si me permitió crear un nuevo anuncio...

espero haberme explicado mejor @jmmartinez1985

**Comment by jmmartinez1985** [comment]
Lo estuve revisando y a mi me funciona bien segun la definicion del requerimiento que plantie, de solo te debe dejar crear anuncios segun la cantidad establecida por la membresia

**Comment by IsrraBanton** [comment]
bueno yo también lo probé, no se que paso con ese usuario, vamos a pensar que estaba muy manoseado ese usuario y fallo jajajaja XD cierra este issue pues, si lo volvemos a ver entonces lo volvemos a levantar.

**Comment by jmmartinez1985** [comment]
Tendria que ver esto live, ya que a mi me funciona bien blood.

**Comment by IsrraBanton** [comment]
cerrado porque no lo puedo volver a generar
