### ISSUE TITLE
Fallá en registro de cuenta

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#175]
Me trate de registrar en el SMA Online  y me da error... Será que introducí mal el captcha? o algo más.

Por favor enviame el registro del ELMAH @IsrraBanton

**Comment by IsrraBanton** [comment]
ya te envio al correo lo de elmah, veo que intentaste loggearte con jo.mi.ma.1985.... pero ese usuario no existe yo lo modifique para que no te llegara spam cuando hacia pruebas... es jo.mi.ma.19851@gmail.com

**Comment by jmmartinez1985** [comment]
Cuando introduces mal el captcha, revienta la app... por el contrario debiera decirte que introduciste mal el captcha

**Comment by IsrraBanton** [comment]
acabo de crear un usuario en el sma online, me mando bien el correo, me registré bien, cuando puse mal el captcha no reventó, me mandó error en el captcha y que corrija, vi todo bien asi que cierro este incidente
