### ISSUE TITLE
Recuperar contraseña no funciona

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#176]
El recuperar contraseña del sitio online no funciona.

Esta algo mal en el SMTP o simplemente no funciona el submit del boton.

**Comment by IsrraBanton** [comment]
no loco, lo que esta jodido es el smtp, si te vas a la tabla de errores, veras que hay algo que lo esta guillando y no se que diablos sea, ningun email sale =S @jmmartinez1985

**Comment by jmmartinez1985** [comment]
Por favor, pegame aqui el WEBCONFIG que esta alla arriba
