### ISSUE TITLE
Formato de recuperar contraseña no esta establecido

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#177]
Esta mal el diseño

![image](https://f.cloud.github.com/assets/5157691/2240811/7140d0a2-9cae-11e3-8b4d-c74a15b813b7.png)

**Comment by IsrraBanton** [comment]
listo ya lo ajuste a la pantalla completa
![image](https://f.cloud.github.com/assets/713416/2246179/8bd03154-9d5f-11e3-9487-cc11dbcf4dc2.png)
