### ISSUE TITLE
Etiqueta de archivo seleccionado no se limpia

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#178]
Cuando estoy creando o editando un anuncio, me permiten subir unas cuantas imagenes. Cada vez que agrego una, hay una etiqueta que indica que he seleccionado un archivo, puesto que si le doy subir me envia un mensaje de error al no haber seleccionado una imagen.
Yo subi el primer archivo, pero me mantuvo la etiqueta que indicaba que habia un archivo seleccionado (ver imagen)
![image](https://cloud.githubusercontent.com/assets/713416/2586840/97299832-ba0c-11e3-8520-5bf24b727d25.png)

cuando le di clic al boton iniciar carga (ya que se entendía como que ya habia un archivo seleccionado) me envió el siguiente error 

![image](https://cloud.githubusercontent.com/assets/713416/2586844/bc580260-ba0c-11e3-803e-74d16f02dfb5.png)

**Comment by jmmartinez1985** [comment]
Procedere a limpiar cuando esto esta en 0 files.

**Comment by jmmartinez1985** [comment]
Listo.
