### ISSUE TITLE
Crear tabla de palabra soeses

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#179]
Crear tabla de palabras soes y generar script

**Comment by IsrraBanton** [comment]
que campos debería llevar esta tabla ??? supongo que un ID, la palabra, y ya??? @jmmartinez1985

**Comment by IsrraBanton** [comment]
ey blood me tienes trabajando doble!!! esto ya estaba listo!!! esta en la base de datos que tu mismo me mandaste! se llama BL_BlackList

**Comment by jmmartinez1985** [comment]
ah offi... no me habia fijado... Listo

Hay un detalle, cuando el review pasa a revision debe indicarlo al usuario que postio, si es asi... se abre tarea.
