### ISSUE TITLE
Footer recent entries

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#18]
Definir que se presentará en esta seccion del footer.

Propongo... 
- ultimos servicios adquiridos.
- ultimos anuncios.
- ultimos feed.
- personas que proveen servicios.
- alguna publicidad.
- algo mas ...

**Comment by IsrraBanton** [comment]
creo que podría ser los últimos anuncios publicados (sin ranking ni nada solo los ultimos publicados)

**Comment by IsrraBanton** [comment]
creación de vista parcial para los ultimos 3 anuncios publicados
