### ISSUE TITLE
Boton de landing page "Conozca Más"

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#19]
A que sección de la pagina ira este boton.

Propongo..
- Acerca del Sitio
- Servicios ofrecidos (Que puede obtener).
- o como hacer un anuncio.

**Comment by IsrraBanton** [comment]
pensé que aquí debe haber una página que explique bien que es el sitio y como empezar a registrar los anuncios, que sea algo como un mini manual de usuario, y lo hacemos al final para poder tener screenshots del sitio

**Comment by IsrraBanton** [comment]
lo linkie a la pagina de about
