### ISSUE TITLE
Error recuperar contraseña

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#195]
Se encontró un mensaje de error en el envio de correo al momento de colocar olvidó contraseña

**Comment by jmmartinez1985** [comment]
Tema de conexion seguro... No habian hecho algo con este incidente, si es asi se reutiliza

**Comment by IsrraBanton** [comment]
cerrado...
EnableSSL = false ;
y eso fue todo para el campeon!
