### ISSUE TITLE
Profile del usuario

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#199]
Si creas una nueva cuenta y te vas al profile te sale una opcion para subir las fotos y completar tus datos. Sin embargo si subes la foto primero que los datos da un error. Hay que solucionar el error o bloquear la vista para que la foto sea lo segundo.
Crear una carpeta con el numero de id de usuario para que cada uno tenga sus fotos de perfil separadas

**Comment by jmmartinez1985** [comment]
Listo.

**Comment by IsrraBanton** [comment]
@jmmartinez1985 cuando hago el pase a produccion tengo que hacer algo especial ? crear carpeta o que?
