### ISSUE TITLE
Contactenos en Footer

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#25]
- Definir que información se establecerá aquí.

Considerar información de la compañía.

**Comment by IsrraBanton** [comment]
creo que se puede hacer una vista parcial de la información de la compañía que esta almacenada en la base de datos y que se imprima igual que en el ejemplo

**Comment by IsrraBanton** [comment]
ey plomo ya hice el js y el controler pero no funcion!!!! =( mañana te pregunto a ver que xopa! agarra mis cambios!
