### ISSUE TITLE
Inclusión en el menu los Anunciantes (Menu no logeado)

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#26]
Se debe incluir los anunciantes, ya que puede haber la posibilidad de que ya la persona ha solicitado servicios de la personas y quizás le ver personas que ofrecen por ejemplo de una categoría en particular.

Creación de método en controlador y vista.

**Comment by jmmartinez1985** [comment]
Se debe desplegar en los anuncios la persona que hizo la publicación.

**Comment by IsrraBanton** [comment]
Listo, agregué el nombre en negrita justo debajo del titulo del anuncio
