### ISSUE TITLE
Los Review debe ser Retracked

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#29]
Esto es necesario ya que quizas el anunciantes quiere escribir un comentario acerca del review (cabe la posibilidad de que recibio un comentario negativo por parte del cliente, y quiere dar su punto de vista).
- Control parental (slang blacklist), de hacerlo debe ser penalizado (Hacer propuestas).
- Evitar colas de mensajes.

Los review deben tener una tabla de comentarios.
- Creacion de Tabla.
- ActionMethod que se encargue de hacer el post del comentario al review. (Solo autenticados).

**Comment by IsrraBanton** [comment]
agregar el campo de estatus a los review

**Comment by IsrraBanton** [comment]
Listo, ya te envio el script de base de datos @jmmartinez1985
