### ISSUE TITLE
Definición de blacklist

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#30]
Se debe definir un blacklist de palabras no permitidas en el sitio.

**Comment by IsrraBanton** [comment]
Crear un xml con palabras no permitidas 
Validar si el texto ingresado es ofensivo

**Comment by jmmartinez1985** [comment]
Se debe crear un custom dataantonation que se alimente del xml o tabla planteada, puede ser muy util un property attribute

**Comment by IsrraBanton** [comment]
Ya cree la tabla, recuerda actualizar el modelo para crear los controlers y vistas que carguen esta tabla!
