### ISSUE TITLE
Creacion de Correo de administrador de Sitio

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#36]
Crear correo de administrador del sitio para que lleguen estas notificaciones.

smaadmin@gmail.com
pwd: smaadmin

**Comment by IsrraBanton** [comment]
el correo smaadmin@gmail.com ya existía y probé diferentes variantes y nada que funcionó asi que el correo que cree es el siguiente: servicemarketinfo@gmail.com
