### ISSUE TITLE
Error en el JS back-to-top

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#45]
El JS back-to-top agrega una imagen de una flecha hacia arriba que al hacerle clic te lleva a la parte superior de la página. La dirección de la imagen está establecida en el archivo JS pero en ocasiones no funciona. Por ejemplo, en la pagina home funciona perfectamente ya que la referencia la hace a smaweb/content/images..... pero si estas en un anuncio donde el url es smaweb/anuncios/edit/1, la imagen no es encontrada por el js ya que intenta hacer algo como smaweb/anuncios/edit/content/images y obviamente este directorio no existe. Hay que ver como se le da la dirección fija a esa imagen.

**Comment by jmmartinez1985** [comment]
Listo arregle el js: $('.imageupcss').attr('src', imageUp);

y una variable para saber donde estoy var imageUp = '@Url.Content("~/images/up.png")'; y cambie la ruta de la imagen.
