### ISSUE TITLE
Creación de vistas de solicitud de servicio

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#5]
Creación de controlador, Views (Edit, Create, List), Verificar si el modelo tiene los dataannnotation

**Comment by jmmartinez1985** [comment]
Solo crear la lista para que los administradores veamos esta información.

Nos debe servir para alguna estadística.

**Comment by IsrraBanton** [comment]
Listo, falta crear las solicitudes de servicio para poder ver esta lista
