### ISSUE TITLE
Creacion de SP Filtro de anuncios

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#52]
Se debe crear un store procedure que filtre los anuncios por:
1. Categoria.
2. Categoria & SubCategoria
3. Categoria & SubCategoria & Descripcion
4. Categoria & SubCategoria & Descripcion & Lugar
5. Descripcion & Lugar
6. Lugar.

**Comment by IsrraBanton** [comment]
Ya hice el sp, te lo paso por correo, también agregué la categoría a la tabla anuncio, voy a tener que tirarme el modelo y arreglar las vistas de anuncios porque tienen que incluir la categoría
