### ISSUE TITLE
Calculo de rating total del Anuncio

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#55]
Crear store procedure que calcule el total obtenido de estrellas.

Tomar en consideracion que solo de pueden dar 5 estrellas.

Por ejemplo hay 2 anuncios: 1 dio 3 estrellas y otro dio 5 estrellas.... Sacar el promedio basado en 10 estrellas que era lo esperado.

**Comment by IsrraBanton** [comment]
Listo, calcula el promedio del ranking utilizando el id del anuncio, el de servicio solicitud y el de review. Te mando por correo el script con el SP
