### ISSUE TITLE
En anuncios detalle no muestra bien descripciones

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#76]
No se muestras las descripciones de País y Subcategoria, MUESTRA ID.

**Comment by IsrraBanton** [comment]
hace falta mostrar algunos otros datos como el área, categoría, etc

**Comment by jmmartinez1985** [comment]
Toma tu bug... jajajaja

**Comment by jmmartinez1985** [comment]
Listo, se cerro.
