### ISSUE TITLE
Modificación de anuncios --- Presentación de Look and Feel

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#8]
Presentar una propuesta de look and feel de como ser vería la presentación para Preview de anuncio, Edición de Anuncio (todo esto es después que se lista de la manera actual y se entra a uno en particular).
1. Creación
2. Edición

**Comment by IsrraBanton** [comment]
Agregué una vista details para cuando un usuario quiere ver el anuncio al completo.
Seguramente mas adelante se le ajusta los estilos, pero este es el primer draft del look and feel de los anuncios.
A @jmmartinez1985 le toca colocar la parte del upload picture.
