### ISSUE TITLE
Olvido su contraseña

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#81]
En la pantalla de iniciar sesión, hay una leyenda que indica que se puede recuperar su contraseña en caso de haberla olvidado. Resulta que el link que supuestamente te ayudará a cambiar la contraseña no lleva a ningun lado. ¿Que habría que hacer para habilitar esto?

**Comment by jmmartinez1985** [comment]
Listo, no esta programado esta secciòn.

Yo me encargo.. Solo que necesitarìa una plantilla de correo.

**Comment by jmmartinez1985** [comment]
Listo, hace falta darle estilo a una nueva plantilla que se llama ResetPasswordComplete.

Pero ya funciona bien y puedes hacer la prueba del flujo completo.
