### ISSUE TITLE
Crear subcategoría redirecciona al index en vez de mostrar el mensaje de creado

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#82]
Cuando creas un subcategoría en el controlador el if (Request.IsAjaxRequest()) viene false y por eso no regresa el json correspondiente, no entiendo por que ocurre esto si en las demas vista esta igual

**Comment by jmmartinez1985** [comment]
Claro... Si es false.. indica que no fue llamado por un jQuery.Ajax, por ende hay que revisar la sección, o verifica si el begin form sea via AJAX.

**Comment by jmmartinez1985** [comment]
Si comentas esto no estas habilitando uso de jquery ajax, por eso no andaba.

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
