### ISSUE TITLE
Error al ingresar a la pantalla edituser

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#83]
el método GetUserImage genera un error al momento de cargar en la pantalla la imagen de perfil

**Comment by jmmartinez1985** [comment]
Necesito, imagen del error, ya que aca no estoy presentando nada.

**Comment by jmmartinez1985** [comment]
Listo, se trabajo con TEMPDATA y manejo de las imagenes ya que se maneja dos acciones para este control.
