### ISSUE TITLE
Colocar los scripts en el archivo SMA.js

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#84]
Los scripts que yo hice los estoy pasando y probando de un vez! Pasa los tuyos @jmmartinez1985

**Comment by jmmartinez1985** [comment]
se paso para siguiente fase

**Comment by jmmartinez1985** [comment]
Trabajando en.

**Comment by jmmartinez1985** [comment]
Se debe seguir con los siguientes scripts, tu @IsrraBanton debieras terminar si ya te enseñe el know how. jajajaja
