### ISSUE TITLE
Posibilidad de eliminar las regiones

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#85]
Veo que las regiones no se usan en ninguna parte del sitio solamente como parte del catálogo de paises, y considero que podemos buscar una tabla de paises de internet y hacer una carga masiva cuestion de no tener que cargarlos todos, al menos que queramos usar los paises para filtrar los paises donde sma tiene presencia, pero suponiendo que la idea es hacer un sitio global nos interesaria que cualquier pais pueda usarlo.

**Comment by jmmartinez1985** [comment]
Habria que ver, si esto es realmente factible.

La idea de regiones era de que se estableciera en SUR Y CENTRO AMERICA.

**Comment by jmmartinez1985** [comment]
Lo cerré por error

**Comment by IsrraBanton** [comment]
hay que ejecutar el script que te enviaré al correo
