### ISSUE TITLE
Error al solicitar Servicio

### ISSUE THREAD

**Issue by jmmartinez1985** [jmmartinez1985/SMASolution#88]
Da error al solicitar servicio

![image](https://f.cloud.github.com/assets/5157691/1509273/c3a3d7e8-4a3f-11e3-8816-0859227aee2e.png)

**Comment by jmmartinez1985** [comment]
Debes revisarlo tu, ya que vi que metiste tus casquitos... jajajajaa
1. se debe hacer es un include los css de bootstrap.
2. verificar compilación.

**Comment by jmmartinez1985** [comment]
![image](https://f.cloud.github.com/assets/5157691/1509284/7ab1a320-4a40-11e3-9a9f-1c7abb01b3ed.png)

Evidencia de cambio.

**Comment by jmmartinez1985** [comment]
Lineas de Error:
1. <img id="logo-footer" src="@Url.Content("~=""/Images/logo2-blue.png")" alt="Service Market">.
2. &uacute;

**Comment by jmmartinez1985** [comment]
Te solucione el problema de la imagen, te queda el de las tildes.

Pienso que con numerical code funcionaría bien.

http://webdesign.about.com/od/localization/l/blhtmlcodes-cz.htm

**Comment by IsrraBanton** [comment]
cerrado
