### ISSUE TITLE
Error al crear la membresia

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#89]
Ingrese como administrador y intenté crear una nueva membresia desde la pantalla de catálogo, y cuando hago clic en el boton crear me envia un error de javascript donde dice que no encuentra el recurso smaweb/membresia/create

**Comment by jmmartinez1985** [comment]
Dice que es un conversion de int to string:

<error
  host="LOGIC-35"
  type="System.InvalidCastException"
  message="Unable to cast object of type 'System.Int32' to type 'System.String'."
  source="System.ComponentModel.DataAnnotations"
  detail="System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.&#xD;&#xA;   at System.ComponentModel.DataAnnotations.StringLengthAttribute.IsValid(Object value)&#xD;&#xA;   at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, ValidationContext validationContext)&#xD;&#xA;   at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)&#xD;&#xA;   at System.Web.Mvc.DataAnnotationsModelValidator.&lt;Validate&gt;d__15.MoveNext()&#xD;&#xA;   at System.Web.Mvc.ModelValidator.CompositeModelValidator.&lt;Validate&gt;d__1.MoveNext()&#xD;&#xA;   at System.Web.Mvc.DefaultModelBinder.OnModelUpdated(ControllerContext controllerContext, ModelBindingContext bindingContext)&#xD;&#xA;   at System.Web.Mvc.DefaultModelBinder.BindComplexModel(ControllerContext controllerContext, ModelBindingContext bindingContext)&#xD;&#xA;   at System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor)&#xD;&#xA;   at System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor)&#xD;&#xA;   at System.Web.Mvc.Async.AsyncControllerActionInvoker.&lt;&gt;c__DisplayClass25.&lt;BeginInvokeAction&gt;b__1e(AsyncCallback asyncCallback, Object asyncState)"
  time="2013-11-18T18:50:06.3451483Z" />

**Comment by jmmartinez1985** [comment]
Quite este dataannotation:

 //[StringLength(4, ErrorMessage = "Por favor verifique el campo días de expiración, sólo se permiten números de hasta 4 dígitos.")]
