### ISSUE TITLE
colocar el rating en la vista GetAnunciosByUser

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#93]
creo que la vista GetAnunciosByUser no tiene el rating, pues al momento de que el usuario se loggea y entra a mis anuncios publicados, las estrellitas del rating no se estan mostrando!

**Comment by jmmartinez1985** [comment]
OK, se le implementará.

**Comment by jmmartinez1985** [comment]
En caso tal pienso que debiera ser un rating global.

**Comment by jmmartinez1985** [comment]
Listo.

**Comment by jmmartinez1985** [comment]
No puedo subir este cambio. Mañana revisamos.
