### ISSUE TITLE
Error en el boton eliminar

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#95]
Error al intentar eliminar un anuncio.
Puse un breakpoint en el controlador y nunca pasa, pero no veo error de javascript

**Comment by jmmartinez1985** [comment]
OK, Reviso y te aviso que pasa y porque pasó. RES

**Comment by jmmartinez1985** [comment]
Ya te resolvi, pero se crea otro bug, ya que no puedes borrar por efectos de foreign keys.

**Comment by jmmartinez1985** [comment]
Ya te resuelvo este!

**Comment by jmmartinez1985** [comment]
Listo.
