### ISSUE TITLE
En la vista editar anuncio no se muestra el pais seleccionado

### ISSUE THREAD

**Issue by IsrraBanton** [jmmartinez1985/SMASolution#98]
En los campos que son dropdownlist de la pantalla editar anuncio, no se selecciona por defecto el valor previamente agregado. Por ejemplo, si creaste un anuncio con pais panama, al momento de editarlo, el dropdown selecciona por defecto Panama.

**Comment by jmmartinez1985** [comment]
OK, necesitas el selectedvalue del dropdown.

Si es eso... Perfecto.

**Comment by jmmartinez1985** [comment]
Listo, pero se genera otro bugs.
